Do not delete coffeescript files for debugging purposes
atom/atom pull request #12713
Opened 2016-09-17 18:52 UTC by Ingramz

Since sourcemaps still refer to `.coffee` files after build, we shouldn't be deleting those from final output directory. Debugging from devtools with latest builds is practically impossible without them.

cc @as-cii

2016-09-17 20:11 UTC, Ingramz commented
CI has trouble retranspiling source map references to files, so I don't know if `compile-cache.js` needs to contain the change it currently has or if the Windows specific block should be omitted. Locally both seem work, though.

2016-09-18 11:44 UTC, XVincentX approved these changes
I approve those changes

2016-09-19 22:58 UTC, damieng commented on src/compile-cache.js
>  function addSourceURL (jsCode, filePath) {
Every one of our compilers already adds the source map and does the file:// work on Windows. I suspect this entire function can be removed.

2016-09-20 08:42 UTC, Ingramz commented on src/compile-cache.js
>  function addSourceURL (jsCode, filePath) {
Verified, yep, it can be removed.

2016-09-20 08:43 UTC, Ingramz commented
There is still trouble with getting devtools to load .coffee files from asar. It will pretty much break as soon as the person building deletes their build directory.

2016-09-21 23:09 UTC, maxbrunsfeld commented
> There is still trouble with getting devtools to load .coffee files from asar.

Yeah, to make this work we would probably need to modify Electron to make the dev tools aware of `.asar` files. I think that instead, we should just remove the source map URLs from the transpiled files that we ship. Eventually, we will stop using coffee-script. Though we may still use Babel to transpile our source files, the output will be pretty easy to debug compared to the output of the coffee-script compiler.

2016-09-21 23:36 UTC, maxbrunsfeld requested changes
@Ingramz are you interested in submitting a different PR to simply remove the source maps from the transpiled files that we ship?

I believe we'd need to change these files:
https://github.com/atom/atom/blob/master/script/lib/transpile-babel-paths.js
https://github.com/atom/atom/blob/master/script/lib/transpile-coffee-script-paths.js

As for this PR, in my opinion it is not worth including the un-transpiled version of every file in the app, especially since there would be some complexity in getting them to display correctly in the dev tools.

2016-09-22 06:09 UTC, damieng commented
I'm not keen on losing the source maps entirely as they're pretty essential for debugging in our current Coffeescript world and even with Babel without them setting breakpoints etc. will be wrong. 

One compromise might be to only include them in local dev builds and not include them in production/release versions.

2016-09-22 06:13 UTC, thomasjo commented
> One compromise might be to only include them in local dev builds and not include them in production/release versions.

I think this is the route we should take, at least until we can find a better solution (which will likely require changes in Electron as @maxbrunsfeld has mentioned).

2016-09-22 16:49 UTC, maxbrunsfeld commented
> I'm not keen on losing the source maps entirely as they're pretty essential for debugging in our current Coffeescript world

They already don't work, right? AFAIK, the only time you'd see coffee-script files are when the coffee-script has been compiled *dynamically*, e.g. non-bundled packages, or Atom's source code when running in dev or test mode.

2016-09-22 20:58 UTC, damieng commented
Some of them do work now but not all it would seem. I need to investigate.

On Thu, Sep 22, 2016, 5:50 PM Max Brunsfeld <notifications@github.com>
wrote:

> I'm not keen on losing the source maps entirely as they're pretty
> essential for debugging in our current Coffeescript world
>
> They already don't work, right? AFAIK, the only time you'd see
> coffee-script files are when the coffee-script has been compiled
> *dynamically*, e.g. non-bundled packages, or Atom's source code when
> running in dev or test mode.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/atom/atom/pull/12713#issuecomment-248961110>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAHQp3sYxmeqWeB96FxlqRjGkr2uHphSks5qsrHCgaJpZM4J_rUV>
> .
>

2016-09-22 22:22 UTC, iolsen commented
I've found that commenting out the unlink of coffeescript files, one of the changes in this PR, has made debugging e.g. pane.coffee work as expected. What about adding a build arg to leave those in place for when you're building locally for dev/debug purposes? Certainly I agree it makes sense to leave them out of the released installers.

2016-09-23 00:07 UTC, maxbrunsfeld commented
> I've found that commenting out the unlink of coffeescript files, one of the changes in this PR, has made debugging e.g. `pane.coffee` work as expected.

> It will pretty much break as soon as the person building deletes their build directory.

:+1: I just reproduced both of these behaviors and am understanding this a little better now. So in our new build scripts, coffee-script files are compiled with source maps, but the source map paths point to a temporary location in the `out` folder of the Atom repository, where the coffee-script files were copied to before being transpiled.

So as long as you keep those temporary files around, the coffee-script files will load correctly in the dev tools. If you remove the temporary files, or run another build (even without installing), the source maps will either stop working or will start pointing to the wrong files.

We *could* add a build flag to opt into this behavior, but it's a pretty fragile and hard-to-explain behavior. And seeing as how it would mostly get used during development, it seems like the existing Dev mode is a better solution to this problem.

Thoughts?

2016-09-26 13:32 UTC, Ingramz commented
Conveniently coffee-script 1.11.0 was released two days ago, which adds support for inline source maps, which should solve problems with referencing source files from asar.

2016-09-26 23:11 UTC, Ingramz commented
I tried coffee-script 1.11.0 and inline sourcemaps do seem to work as intended. Made appropriate changes to this PR, requires #12780 to be merged first.

2016-09-29 20:55 UTC, maxbrunsfeld commented
@Ingramz it looks like one `CompileCache` test is failing:

```
CompileCache
  addPathToCache(filePath, atomHome)
    when the given file is coffee-script
      it compiles the file with coffee-script and caches it
        TypeError: output.replace is not a function
          at Object.exports.compile (/Users/distiller/atom/src/coffee-script.js:44:17)
          at compileFileAtPath (/Users/distiller/atom/src/compile-cache.js:77:31)
          at .<anonymous> (/Users/distiller/atom/spec/compile-cache-spec.coffee:67:24)
```

Could you take a look at that?

2016-09-30 12:25 UTC, Ingramz commented
@maxbrunsfeld should be good now.

2016-09-30 19:21 UTC, maxbrunsfeld approved these changes

2016-10-01 21:52 UTC, merged

2016-10-01 21:53 UTC, maxbrunsfeld commented
Thanks so much for investigating this @Ingramz!

2016-10-02 00:00 UTC, Ingramz commented
@maxbrunsfeld for this to kick in, I suspect that compile-cache needs to be cleared on CI.

2016-10-04 00:11 UTC, maxbrunsfeld commented
Great point @Ingramz. Done.