Fix for #10474
atom/atom pull request #12922
Opened 2016-10-09 20:01 UTC by stereobooster

2016-10-10 07:14 UTC, thomasjo requested changes

2016-10-10 07:14 UTC, thomasjo commented on src/text-editor.coffee
> +    if windowCloseRequested && projectHasPaths
Change `&&` to `and`.

2016-10-10 07:50 UTC, stereobooster commented on src/text-editor.coffee
> +    if windowCloseRequested && projectHasPaths
done

2016-10-12 15:38 UTC, stereobooster commented
@thomasjo anything else? Squish commits or something?

2016-10-12 17:00 UTC, thomasjo commented
This seems OK to me, but I'll let someone else have a look as well. /cc @atom/feedback

2016-10-26 23:35 UTC, iolsen commented
💯 Awesome! Thanks for this contribution!

Merging now and this will be in the 1.13 beta.

2016-10-26 23:35 UTC, merged