make script/build parse args first and supports -h options
atom/atom pull request #12979
Opened 2016-10-14 06:48 UTC by liuderchi

1. Related issue is [#12978](https://github.com/atom/atom/issues/12978)
2. changes:
  - parse args first then checks module dependencies to avoid slow response for `script/build --help`
  - add args alias `-h` for `--help`

2016-10-14 20:46 UTC, winstliu requested changes

2016-10-14 20:46 UTC, 50Wliu commented on script/build
>  const yargs = require('yargs')
This will fail without bootstrap.

2016-10-15 04:21 UTC, liuderchi commented on script/build
>  const yargs = require('yargs')
These imports (line 5-12) are not removed but __moved__ after `argv` definition (line 14-24).

2016-10-17 02:42 UTC, liuderchi commented on script/build
>  const yargs = require('yargs')
thanks for your review.
Maybe I should find another way to run `build --help` without external library.
this PR will be closed

2016-10-17 02:42 UTC, closed without merging