Raising exceptions in test mode (Issue: #10079)
atom/atom pull request #13119
Opened 2016-10-31 20:14 UTC by SahilC

2016-10-31 20:35 UTC, 50Wliu commented on src/atom-environment.coffee
> +      testMode: @inTestMode()
To be consistent with the rest I would change this to be `@testMode` instead.

2016-11-01 04:27 UTC, SahilC commented
I've made the requested changes, could someone verify if everything is ok?

2016-11-01 07:10 UTC, thomasjo commented
Can you explain the purpose of this PR? How is this different to [spec mode](https://github.com/atom/atom/blob/8229924b96497f0d0d0db47355d3e821c58a77ec/src/atom-environment.coffee#L427-L429)?

2016-11-01 07:14 UTC, thomasjo commented
OK, I see from the title that this is meant to fix #10079. Next time, please add all relevant details to the description body of the PR. I'll add some review comments for the remainder of my review.

2016-11-01 07:17 UTC, thomasjo requested changes

2016-11-01 07:17 UTC, thomasjo commented on src/atom-environment.coffee
> +      testMode: @testMode
This needs to be removed. We already have this in the form of `specMode`.

2016-11-01 07:17 UTC, thomasjo commented on src/atom-environment.coffee
> +
Same as earlier, needs to be removed.

2016-11-01 07:17 UTC, thomasjo commented on src/package-manager.coffee
> +      configDirPath, @devMode, safeMode, @testMode, @resourcePath, @config, @styleManager,
`@testMode` needs to be removed.

2016-11-01 07:17 UTC, thomasjo commented on src/package-manager.coffee
> +        @commandRegistry, @keymapManager, @devMode, @testMode, @notificationManager,
Bye bye, `@testMode`

2016-11-01 07:17 UTC, thomasjo commented on src/package.coffee
> +      @keymapManager, @devMode, @testMode, @notificationManager, @grammarRegistry, @themeManager,
You know the drill by now 😄

2016-11-01 07:17 UTC, thomasjo commented on src/package.coffee
> +            if @testMode
Change `@testMode` to `@specMode`.

2016-11-01 14:58 UTC, 50Wliu commented
Ah hah, I thought there was a specMode already defined somewhere...but I didn't see anywhere in the diff :P.

2016-11-01 15:22 UTC, SahilC commented
Yeah, I was confused about that too! Should I just rename everything to specMode?

2016-11-01 15:27 UTC, thomasjo commented
@SahilC It already exists, so remove almost all additions (as per my review comments). Keep the change package.coffee, but rename the `@testMode` there to `@specMode`.

2016-11-01 15:41 UTC, SahilC commented
But specMode isn't being passed to package.coffee's constructor. Am I missing something?

2016-11-01 15:48 UTC, thomasjo commented
@SahilC Sorry I should have looked at the diffs more closely, but you can use [`atom.inSpecMode()`](https://atom.io/docs/api/v1.11.2/AtomEnvironment#instance-inSpecMode).

2016-11-01 15:49 UTC, thomasjo commented on src/package.coffee
> +            if @testMode
Sorry I was mistaken earlier, but `@testMode` can be replaced with `atom.inSpecMode()`.

2016-11-01 16:10 UTC, SahilC commented
I've removed all occurrences of testMode, and replaced the check with atom.inSpecMode(). Wouldn't it be more consistent to use a variable rather than actually calling that function directly?

2016-11-01 16:15 UTC, thomasjo commented
I don't think it's worth adding the necessary changes for that given that we only check if we're in spec mode on a single line. I'd argue we should rather remove `@devMode` when we get around to converting this to JS.

This looks good to me now!

2016-11-01 16:15 UTC, thomasjo approved these changes

2016-11-01 16:59 UTC, SahilC commented
Cool, thanks!

2016-11-07 23:47 UTC, maxbrunsfeld commented on src/package.coffee
> +              raise error
This should be `throw error`.

2016-11-07 23:48 UTC, maxbrunsfeld commented
Thanks for looking into this problem @SahilC! Just one comment 👆 .

2016-11-19 05:35 UTC, joh1234 commented
Great, thanks. https://goo.gl/JBljdR

2017-01-18 18:46 UTC, closed without merging