Resize pane
atom/atom pull request #16428
Opened 2017-12-22 00:04 UTC by ernesto28

### Requirements

Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Description of the Change

Atom gets into a perplexing state for some people (for example) whether by some combination of keys or package actions where there is only one pane, but it does not take up the full width of the editor window. This changes in this Pull request prevent atom to get into this state.

### Alternate Designs

NA

### Why Should This Be In Core?

Fixes a bad behavior in atom UI

### Benefits

Added test for the new code
Better experience in atom UI

### Possible Drawbacks

None that I can think of.

### Applicable Issues

It's applicable to #11673

2017-12-22 01:08 UTC, winstliu requested changes
Thanks for taking this on!  I've left some minor review comments below.

2017-12-22 01:08 UTC, 50Wliu commented on spec/pane-container-element-spec.coffee
> +      it "increases the size of the pane", ->
These spec descriptions are incorrect - can you change them?

2017-12-22 01:08 UTC, 50Wliu commented on src/pane.js
> +    if (this.getContainer().getPanes().length > 1){
Style: space before opening bracket

2017-12-22 01:08 UTC, 50Wliu commented on src/pane.js
> +    if (this.getContainer().getPanes().length > 1){
Style: space before opening bracket

2017-12-22 01:08 UTC, 50Wliu commented on spec/pane-container-element-spec.coffee
> +      it "decreases the size of the pane", ->
Same here

2017-12-22 01:08 UTC, 50Wliu commented on spec/pane-container-element-spec.coffee
> +        expect(singlePane.getFlexScale()).toBe 1
Newline should be added at the end of the file

2017-12-22 01:08 UTC, 50Wliu commented on spec/pane-container-element-spec.coffee
> +  describe "one pane resizing", ->
How about `when only a single pane is present`

2017-12-22 01:22 UTC, ernesto28 commented
@50Wliu Thanks, I'll correct them

2017-12-22 01:44 UTC, 50Wliu commented
Thanks!  You'll also need to remove the package-lock.json files you checked in as Atom won't build if they're present.

2017-12-22 01:49 UTC, ernesto28 commented
Got it, I'll delete them

2017-12-22 02:13 UTC, winstliu approved these changes

2018-03-09 07:38 UTC, merged

2018-03-09 07:38 UTC, as-cii commented
Looks great, nice work! ⚡️