Add additional dependencies for linux
atom/atom pull request #16812
Opened 2018-02-21 22:13 UTC by ungb

# TODO

/cc @Arcanemagus

2018-02-21 22:19 UTC, daviwil commented
Any idea what changes caused these dependencies to be needed?

2018-02-21 22:27 UTC, Arcanemagus commented
I think they have _always_ been needed, it's just they are installed by default in most Desktop distributions.

I can confirm from building a [minimal install for CI purposes](https://hub.docker.com/r/arcanemagus/atom-docker-ci/) that `libxss1` and `libasound2` are required. The base image that I am using there has `libx11-xcb1` and `libxkbfile1` installed automatically already, still checking that those aren't included transitively from another dependency.

Note that this fixes:
https://github.com/atom/atom/issues/4114 (Supposedly fixed in https://github.com/atom/atom/commit/f431bb6396f9f5c5c5f98fa08040dc3410896d69, but at minimum `libasound2` was reported there but missed)
https://github.com/atom/atom/issues/13591 (Unstated, but supposedly an Ubuntu 16.04 install of some sort)
https://github.com/atom/atom/issues/16659 (Some minimal Ubuntu base image)

2018-02-21 22:32 UTC, Arcanemagus commented
Ah, looks like I'm getting `libx11-xcb1` and `libxkbfile1` from bringing in `xvfb`.

2018-02-21 22:43 UTC, Arcanemagus commented
Note that this is the list from the Chrome 64.0.3282.167-1 `.deb`:
```
Depends: ca-certificates, fonts-liberation, gconf-service, libappindicator1, libasound2 (>= 1.0.16), libatk-bridge2.0-0 (>= 2.5.3), libatk1.0-0 (>= 1.12.4), libc6 (>= 2.15), libcairo2 (>= 1.6.0), libcups2 (>= 1.4.0), libdbus-1-3 (>= 1.1.4), libexpat1 (>= 2.0.1), libfontconfig1 (>= 2.11), libgcc1 (>= 1:3.0), libgconf-2-4 (>= 3.2.5), libgdk-pixbuf2.0-0 (>= 2.22.0), libglib2.0-0 (>= 2.28.0), libgtk-3-0 (>= 3.9.10), libnspr4 (>= 2:4.9-2~), libnss3 (>= 2:3.22), libpango-1.0-0 (>= 1.14.0), libpangocairo-1.0-0 (>= 1.14.0), libstdc++6 (>= 4.6), libx11-6 (>= 2:1.4.99.1), libx11-xcb1, libxcb1 (>= 1.6), libxcomposite1 (>= 1:0.3-1), libxcursor1 (>> 1.1.2), libxdamage1 (>= 1:1.1), libxext6, libxfixes3, libxi6 (>= 2:1.2.99.4), libxrandr2 (>= 2:1.2.99.3), libxrender1, libxss1, libxtst6, lsb-release, wget, xdg-utils (>= 1.0.2)
```

Note that it includes the following:
```
libxcb1 (>= 1.6)
libxss1
libx11-xcb1
libasound2 (>= 1.0.16)
```

Since Atom runs on Electron, which is based on Chrome, I'd say that's a pretty good indicator that these are needed 😉.

2018-02-22 01:17 UTC, daviwil approved these changes

2018-02-22 01:18 UTC, daviwil commented
Thanks a lot for all the background details!  This all sounds great to me and the changes look fine.

2018-02-22 08:03 UTC, Ben3eeE commented
> Edit: libxkbfile1 isn't in the list from Chrome, so I'd say that's the only one that there is any question on.

`atom-keymap` and `keyboard-layout` use `libxkbfile` since Atom 1.12 or 1.13 https://github.com/atom/atom-keymap/pull/152/files and https://github.com/atom/keyboard-layout/pull/18/files

2018-02-22 17:12 UTC, Arcanemagus requested changes

2018-02-22 17:12 UTC, Arcanemagus commented on resources/linux/debian/control.in
> +Depends: git, gconf2, gconf-service, libgtk2.0-0, libudev0 | libudev1, libgcrypt11 | libgcrypt20, libnotify4, libxtst6, libnss3, python, gvfs-bin, xdg-utils, libcap2, libx11-xcb1, libxss1, libasound2
I would change the `libasound2` dependency to have the same minimum version as the Chrome package: `libasound2 (>= 1.0.16)`.

2018-02-22 17:15 UTC, Arcanemagus commented on resources/linux/debian/control.in
> +Depends: git, gconf2, gconf-service, libgtk2.0-0, libudev0 | libudev1, libgcrypt11 | libgcrypt20, libnotify4, libxtst6, libnss3, python, gvfs-bin, xdg-utils, libcap2, libx11-xcb1, libxss1, libasound2
On that note, you _may_ want to add a minimum version to the following:
* `libnss3` -> `libnss3 (>= 2:3.22)`

2018-02-22 22:54 UTC, ungb commented
I've made the changes requested. Probably won't have much more time this week to test this.  I didn't see any issues on ubuntu stock when testing on there, but of course, these deps are already on the system.  I wanted to test this on the docker scenario but didn't know how to put the `.deb` file in a place where you can wget it.   

This isn't super urgent but I'll try to get around to it next week.

2018-02-22 22:55 UTC, Arcanemagus approved these changes

2018-02-22 22:57 UTC, Arcanemagus commented
You can test it locally using [COPY](https://docs.docker.com/engine/reference/builder/#copy) in the Dockerfile (or by firing up a minimal VM 😆).

2018-02-22 23:01 UTC, Arcanemagus commented
Looks like Travis is having some network issues.

Thanks for getting this put up btw!

2018-03-05 17:36 UTC, daviwil commented
Restarting the TravisCI build to see if we can get this merged :)

2018-03-05 18:12 UTC, merged