Update how softWrap option behaves
atom/atom pull request #18704
Opened 2019-01-16 03:28 UTC by marcel0ll

### Issue or RFC Endorsed by Atom's Maintainers

#11303 

### Description of the Change

Updated how soft wrapping works on atom. Now there are 5 options:

- disabled: Editor wont soft wrap

- window: Editor will wrap at window's width

- preferredLineLength: Editor will wrap at the option  preferred line length
value

- minWindowOrPll: Editor will wrap at the minimum value of window's width
and preferred line length option value

- maxWindowOrPll: Editor will wrap at the maximum value of window's width
and preferred line length option value

This was changed due to the fact that atom would not respect the now removed option "Soft wrap ap preferred line length" when the window was smaller than the preferred line length.

### Alternate Designs

I considered just changing the code that forced atom to wrap lines at the minimum value of preferred line length and window size, but there was already an issue that had a better suggestion than my idea as it was pointed out to me. 

### Possible Drawbacks

Maybe backward compatibility with current atom configuration as the type from softWrap changed from Boolean to String.

### Verification Process

I opened atom in dev mode.
Set soft wrap to 'disabled' and checked the result.
Set soft wrap to 'window' and checked the result.
Set soft wrap to 'preferredLineLength', set preferred line length to 1 and checked the result.
Set soft wrap to 'preferredLineLength', set preferred line length to 100 and checked the result.
Set soft wrap to 'minWindowOrPll', set preferred line length to 1 and checked the result.
Set soft wrap to 'minWindowOrPll', set preferred line length to 100 and checked the result.
Set soft wrap to 'maxWindowOrPll', set preferred line length to 1 and checked the result.
Set soft wrap to 'maxWindowOrPll', set preferred line length to 100 and checked the result.

### Release Notes

- Updated softWrap option to allow more control on how atom wraps the code

2019-01-18 01:18 UTC, rsese commented
Thanks @0tho! Someone from the team will take a look as soon as they can.

2019-02-14 14:45 UTC, 0tho commented
@rsese Is there anything I can do to help the review process?

2019-02-14 17:13 UTC, rsese commented
Hey @0tho :wave: If anything more is needed from your end, the person that ends up reviewing will comment here so nothing for now.  Your pull request is on the team's list to review as soon as they can, but we can't promise a timeframe for review.

2019-05-27 16:34 UTC, 0tho commented
Not sure what the error on appveyor means and how I can fix it. Any help would be appreciated

2019-05-27 18:33 UTC, 50Wliu commented
Network error. I restarted the build.

2019-05-31 21:13 UTC, rafeca commented
Hey! 👋

We have recently started using [`prettier`](http://prettier.io/) and this has caused major style changes on the Atom JS codebase (you can check [the related PR](https://github.com/atom/atom/pull/19391)).

This is good news: now the Atom code is more consistent and it's much easier to re-format the code to follow the codestyle (now you only need to run `script/lint --fix`).

This change caused conflicts on your PR that we have automatically solved, hope you don't mind 😄

With ❤️, the Atom team.

2020-02-16 21:23 UTC, ghost approved these changes

2021-01-20 13:16 UTC, marcel0ll commented
Is there anything else that could be done to merge this PR? Or if this is not something that won't ever be merged for some reason, let's just close it.

It has been 2 years since I opened this PR.

2021-02-03 15:11 UTC, michael-camilo commented
Please, someone, merge this PR !!

2021-02-03 19:37 UTC, ThatXliner commented
> Please, someone, merge this PR !!

There are conflicting files

2021-02-03 21:08 UTC, marcel0ll commented
There weren't for years

2021-02-03 22:35 UTC, ThatXliner commented
Welp, there are now

2021-02-18 18:14 UTC, sadick254 requested changes

2021-02-18 18:14 UTC, sadick254 commented on src/text-editor.js
> +        case 'minWindowOrPll':
```suggestion
        case 'minWindowOrPreferredLineLength':
```
I know this is a long one but it is clear on what the option is supposed to achieve.

2021-06-03 16:45 UTC, sadick254 commented
Hey @marcel0ll, I know this PR has been open for a long time now (2yrs). Apologies that we didn't get to it on time. Thank you for all the hard work you have done on the PR. However, I don't think this would be merged.

The current options that we have `preferredLineLength` and `window width` wrap are sufficient for soft wrapping. Adding 2 more options to me looks like overkill, it also adds complexity to the wrapping behaviour.

Thank you again for your contribution.

2021-06-03 16:45 UTC, closed without merging

2021-06-03 16:48 UTC, marcel0ll commented
Hey @sadick254, no problem. I am honestly glad that this had some closure. Thank you for taking the time to make the previous review and now for closing the PR.