Recreate #15175
atom/atom pull request #22541
Opened 2021-06-04 12:06 UTC by icecream17

See #15175

2021-06-04 14:00 UTC, sadick254 reviewed
The changes look good. Do we know what events that lead to the error?

2021-06-04 14:02 UTC, icecream17 commented
From what I gather about #15172 we don't know why the error happened.

2021-06-04 14:08 UTC, sadick254 commented
I think a good approach would be to display the error as a notification. This way we can have visibility when the error occurs. A user will be able to create an issue from the notification modal. See https://flight-manual.atom.io/api/v1.57.0/NotificationManager/

2021-06-04 15:13 UTC, icecream17 commented
Is the console.error unnecessary now that there's a notification?

2021-06-04 15:53 UTC, sadick254 commented
The `console.error` is fine.

2021-06-04 16:02 UTC, UziTech commented
I think [`addFatalError`](https://flight-manual.atom.io/api/v1.57.0/NotificationManager/#instance-addFatalError) might be better so the button to easily create an issue appears.

2021-06-04 17:24 UTC, sadick254 requested changes
I agree with @UziTech

2021-06-04 17:24 UTC, sadick254 commented on src/state-store.js
> +            atom.notifications.addError('Error loading database', {
```suggestion
            atom.notifications.addFatalError('Error loading database', {
```

2021-06-04 17:24 UTC, sadick254 commented on src/state-store.js
> +          atom.notifications.addError('Could not connect to indexedDB', {
```suggestion
          atom.notifications.addFatalError('Could not connect to indexedDB', {
```

2021-06-07 05:05 UTC, sadick254 approved these changes

2021-06-07 05:05 UTC, merged