Fixed command to install Atom dependencies on Ubuntu
atom/atom pull request #22697
Opened 2021-07-06 09:02 UTC by hwittenborn

The current version for installing dependencies on Ubuntu for the prebuilt `.tar.gz` package has some commas in between package names, which causes issues when installing with APT, as can be seen below:

![image](https://user-images.githubusercontent.com/74838472/124572967-b86d2080-de0e-11eb-86dc-6e9d444e368b.png)

The new version removes the commas, as well as puts the command on a separate line, allowing the clipboard button to copy the command to work properly.

2021-07-08 11:31 UTC, mfonville commented
Thanks, you are right that with the commas the command is broken

2021-07-08 16:27 UTC, sadick254 requested changes

2021-07-08 16:27 UTC, sadick254 commented on README.md
> +sudo apt install git libasound2 libcurl libgbm1 libgcrypt20 libgtk-3-0 libnotify4 libnss3 libglib2.0-bin xdg-utils libx11-xcb1 libxcb-dri3-0 libxss1 libxtst6 libxkbfile1
```suggestion
sudo apt install git libasound2 libcurl4 libgbm1 libgcrypt20 libgtk-3-0 libnotify4 libnss3 libglib2.0-bin xdg-utils libx11-xcb1 libxcb-dri3-0 libxss1 libxtst6 libxkbfile1
```

2021-07-11 04:51 UTC, DeeDeeG approved these changes
Removing commas is correct here, and this updated command works for me using Ubuntu 18.04 and Ubuntu 20.04 in Docker.

2021-07-14 05:00 UTC, sadick254 approved these changes

2021-07-14 05:00 UTC, merged